services:
  - type: web
    name: ilana-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && pip uninstall -y numpy && pip install "numpy==1.24.3"
    startCommand: cp -r config/* api/ && cp -r ml-models/* api/ && cd api && mkdir -p logs && touch logs/ilana_api.log && python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PUBMEDBERT_ENDPOINT_URL
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: 8000